version: '2.4'

services:
  web:
    build:
      target: dev
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
      - '9229:9229'
      - '8080:8080'
    environment:
      - NODE_ENV=development
  
  mongo:
    ports:
        - '27018:27018'
    volumes:
      - dev-mongo-data:/data/db

volumes:
  dev-mongo-data: