version: '2.4'

services:

  web:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - DB_URI=mongodb://root:root@mongo:27017
      - DB_NAMESPACE=storybuilder
    ports:
      - '3000:3000'
    depends_on:
      mongo:
        condition: service_healthy
    tty: true
  
  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
        - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    tty: true