# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  compose-up:
    docker:
      - image: cimg/base:2021.11
    
    steps:
      # Checkout the code as the first step.
      - setup_remote_docker:
          version: 20.10.11
      - checkout
      - run:
          name: Compose Up
          command: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  sample:
    jobs:
      - compose-up
      # For running simple node tests, you could optionally use the node/test job from the orb to replicate and replace the job above in fewer lines.
      # - node/test
